Добавил Функциональность «Общие фильмы»
culto90/java-filmorate pull request #14
Opened 2022-07-22 16:37 UTC by culto90

Добавил Функциональность «Общие фильмы»

2022-07-22 17:51 UTC, Solovoi-Ivan requested changes

2022-07-22 17:51 UTC, Solovoi-Ivan commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultFilmService.java
> +
Можно убрать код в 114-120 строках. При вызове метода userStorage.getById() в строках 111, 112 происходит идентичная валидация.

2022-07-22 18:00 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultFilmService.java
> +
не совсем согласен, т.к. считаю, что данный метод не должен полагаться на реализацию сторейджа. Если сторейдж поменяется, то данный метод будет работать не правильно без этих проверок. А в такой реализации будет корректно отрабатывать при null значениях

2022-07-22 18:05 UTC, Solovoi-Ivan approved these changes

2022-07-23 12:59 UTC, SergeyTsaregorodtsev approved these changes

2022-07-23 13:00 UTC, merged