add-director rev.1
culto90/java-filmorate pull request #15
Opened 2022-07-22 19:12 UTC by SergeyTsaregorodtsev

2022-07-23 12:51 UTC, culto90 requested changes
В целом все клево, но надо исправить некоторые моменты, если нужны будут комментарии предлагаю обсудить это в слаке.

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +        getById(directorId);        // проверяем, существует ли такой директор
Не согласен что это похоже на проверку. Данный код полагается на конкретную реализацию репозитория. В случае, если данная реализация поменяется, то не будет гарантий что данный метод будет работать корректно. Предлагаю реализовать явную проверку, таким образом данный метод будет гарантированно верно работать.

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +                films.sort(new Comparator<Film>() {
Можно использовать стримы и лямды, так выглядит локаничнее, а делает то же самое: films.stream().        .sorted(Comparator.comparing(Film::getLikeCount).reversed())...

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +                films.sort(new Comparator<Film>() {
здесь тоже можно сделать стримом и лямдой, будет локаничнее

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/DirectorStorage.java
> +public interface DirectorStorage extends Storage<Director,Long> {
пропущен пробел Director и Long

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/FilmStorage.java
> +    List<Film> getDirectorFilms(long directorId);
Хорошее название метода, но может быть getFilmsByDirectorId несло бы больше смысловой нагрузки

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "SELECT * FROM directors ORDER BY DIRECTOR_ID";
Не рекомендовал бы использовать * в селектах, если по каким-то причинам полей в таблице станет больше, то они так или иначе будут извлекаться из БД, а использоваться не будут, тем самым потребляя ресурсы напрасно. + придерживался бы стиля, когда ключевые слова в верхнем регистре, названия полей и таблиц в нижнем регистре. + Еще есть минус такого объявления переменной она будет создаваться каждый раз, когда будет вызываться данный метод тем самым раз за разом потребляя ресурсы. Рекомендую сделать ее строковой константой.

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        try {
данный код можно улучшить избавившись от конструкции трай кетч, которая громоздкая и только увеличивает сложность кода. Можно получить объект методом query. + заменить на лямду имплементацию анонимного класса, так выглядело бы локаничнее.List<Director> directors = jdbcTemplate.query(SELECT, this::mapRowToDirector, id);
        if (directors.size() == 0) {
            return null; // or else
        } else {
            return feeds.get(0);
        }

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        final String sqlQuery = "SELECT * FROM directors WHERE DIRECTOR_ID = ?";
как и выше, лучше бы сделать константой класса

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "INSERT INTO directors (NAME) values (?)";
как и выше, лучше бы сделать константой класса

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        jdbcTemplate.update(new PreparedStatementCreator() {
почему бы ля инсерта не использовать более локаничную запись через SimpleJdbcInsert можно подсмотреть в DbFilmStorage в методе insertFilm, по мне так чем легче читать, тем лучше да и строчек меньше печать нужно)

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "UPDATE directors SET NAME = ? WHERE DIRECTOR_ID = ?";
как и выше, лучше бы сделать константой класса

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "DELETE FROM directors WHERE DIRECTOR_ID = ?";
как и выше, лучше бы сделать константой класса

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +    public void removeAll() {
метод не имплементирован

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +            film.setDirectors(applyDirectors(film.getId()));
Хорошее решение выносить в отдельные методы получение саб-сущности

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        String sqlQuery =   "SELECT film_directors.DIRECTOR_ID, directors.NAME FROM film_directors " +
надо сделать статической переменной класса

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        String sqlQuery =   "SELECT films.* FROM film_directors " +
должна быть константой класса

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        String sqlQuery =   "SELECT films.* FROM film_directors " +
и явно прописать поля, которые требуются для извлечения. А вообще, что бы не дублировать реализацию, можно извлечь только идентификаторы фильмов и воспользоваться стримом и готовым методом getById что бы вернуть заполненные сущности фильмов как вариант.

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        jdbcTemplate.update(sqlQuery, film.getId());
следует инкапсулировать в методе вставки директоров

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        return updatedFilm;
return this.getById(film.getId()); Идея этой удаленной строчки в том, что мы извлекаем готовый объект из БД после того как поработали с его дочерними сущностями. В случае, если придут новые режиссеры в виде коллекции, их вставят в БД, а потом эту же коллекцию сетнут фильму, то сетнутные режиссеры будут без ИД и чего бы то ни было еще, по этой причине например как с жанрами в начале была вставка если это было не обходимо (реализована проверка) а затем благодаря методу getById извлекался объект целиком со всеми дочерними сущностями

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +                String sqlQuery = "MERGE INTO film_directors (FILM_ID, DIRECTOR_ID) VALUES (?,?)";
надо сделать константой класса

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +        return directorStorage.add(director);
реализовал бы на уровне сервиса проверки, которые бы не позволяли вставлять null - объекты. Если имплементация стораджа поменяется, данный метод тоже свалится. В протвном случае сторадж должен подкидывать эксепшон сюда, что бы здесь его 100% можно было отработать - но это как по мне не очень вариант.

2022-07-23 12:51 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/models/Director.java
> +    @NotBlank(message = "Имя режиссёра не может быть пустым.")
Валидации бы таки перенес на уровень ДТО, тем самым это бы не сковывало применение данного класса Притом не использовал бы вообще здесь ломбок вовсе, т.к. это основная сущность приложения и ее методы подобно библиотечным должны быть прописаны явно.

2022-07-24 13:35 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/models/ErrorResponse.java
> +public class ErrorResponse {
Заменил на ErrorInfo.

2022-07-24 13:36 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/models/Film.java
> +    public void setDirectors(List<Director> directors) {
Да, действительно. Использовал void setDirectorList(List directors).

2022-07-24 13:36 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/rest/controllers/DirectorController.java
> +    DirectorService directorService;
Исправил.

2022-07-24 13:37 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/rest/controllers/FilmController.java
> +        if (!(sortBy.equals("year") || sortBy.equals("likes"))) {
Перенёс проверку в сервис.

2022-07-24 13:38 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/rest/converters/FilmDtoToFilmConverter.java
> +        film.setDirectors(filmDto.getDirectors());
Заменил на setDirectorList.

2022-07-24 13:43 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +                String sqlQuery = "MERGE INTO film_directors (FILM_ID, DIRECTOR_ID) VALUES (?,?)";
Исправлено.

2022-07-24 13:44 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/rest/handlers/GlobalControllerExceptionHandler.java
> +        return new ErrorResponse(String.format("Ошибка: %s", e.getMessage()));
Использовал ErrorInfo.

2022-07-24 13:44 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/rest/handlers/GlobalControllerExceptionHandler.java
> +    public ErrorResponse handleDirectorNotFoundException(final DirectorNotFoundException e) {
Использовал ErrorInfo.

2022-07-24 13:47 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +                films.sort(new Comparator<Film>() {
Поменял на лямбды, но без стримов. Эти темы ужасно были раскрыты в Практикуме - пока плаваю в них.

2022-07-24 13:48 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +                films.sort(new Comparator<Film>() {
Перевёл на лямбду.

2022-07-24 13:48 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/DirectorStorage.java
> +public interface DirectorStorage extends Storage<Director,Long> {
Исправлено.

2022-07-24 13:48 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/FilmStorage.java
> +    List<Film> getDirectorFilms(long directorId);
Исправлено.

2022-07-24 13:49 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "SELECT * FROM directors ORDER BY DIRECTOR_ID";
Изменил строку, перенёс в статик.

2022-07-24 13:49 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        try {
Переделал в лямбду, но оставил query - иначе потом ревьюер ещё раз заставит переделать.

2022-07-24 13:50 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        final String sqlQuery = "SELECT * FROM directors WHERE DIRECTOR_ID = ?";
Перевёл строку в константу.

2022-07-24 13:50 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "INSERT INTO directors (NAME) values (?)";
Перевёл строку в константу.

2022-07-24 13:50 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "UPDATE directors SET NAME = ? WHERE DIRECTOR_ID = ?";
Перевёл строку в константу.

2022-07-24 13:50 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        String sqlQuery = "DELETE FROM directors WHERE DIRECTOR_ID = ?";
Перевёл строку в константу.

2022-07-24 13:51 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +    public void removeAll() {
Имплементировал.

2022-07-24 13:51 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        String sqlQuery =   "SELECT film_directors.DIRECTOR_ID, directors.NAME FROM film_directors " +
Перевёл строку в константу.

2022-07-24 14:15 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        String sqlQuery =   "SELECT films.* FROM film_directors " +
Хорошая идея! Исправил. Извлекаю только film_id, затем формирую список через getById. Можно было бы через стрим, но не осилю пока. Строка - в константах.

2022-07-24 14:25 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbDirectorStorage.java
> +        jdbcTemplate.update(new PreparedStatementCreator() {
C SimpleJdbcInsert нужно ещё Map<String, Object> DirectorToMap сочинять... Не думаю, что сильно короче будет)

2022-07-24 14:34 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        jdbcTemplate.update(sqlQuery, film.getId());
Перенёс в void insertDirectors(List<Director> directors, long filmId).

2022-07-24 14:46 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +        return directorStorage.add(director);
Реализовал выброс исключения как в FilmService.

2022-07-24 15:26 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/models/Director.java
> +    @NotBlank(message = "Имя режиссёра не может быть пустым.")
Добавил уровень ДТО, перенёс валидацию туда. Убрал ломбок из модели Director.

2022-07-24 15:34 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +        getById(directorId);        // проверяем, существует ли такой директор
Реализована явная проверка на уровне сервиса (возврат null из БД).

2022-07-24 15:51 UTC, SergeyTsaregorodtsev commented
Внес исправления.

2022-07-24 15:57 UTC, culto90 approved these changes
Клевая работа, молодец!

2022-07-24 16:08 UTC, MishaH9201 commented
good

2022-07-24 16:17 UTC, MishaH9201 approved these changes

2022-07-24 16:18 UTC, merged