рекомендаци
culto90/java-filmorate pull request #19
Opened 2022-07-24 16:34 UTC by MishaH9201

2022-07-24 16:50 UTC, culto90 requested changes
Есть пара моментов для улучшения, в остальном все огонь!

2022-07-24 16:50 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultRecommendationsService.java
> +@Autowired
нарушен кодстайл, надо поправить

2022-07-24 16:50 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultRecommendationsService.java
> +@Override
нарушен кодстайл, надо поправить

2022-07-24 16:50 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +    private static final String SELECT_FILMS_FRIENDS = "SELECT * FROM FILMS WHERE FILM_ID IN " +
использовать * не оптимально, если таблица "подрастет" то данный репозиторий будет эти данные извлекать, но использовать не будет. Лучше перечислять конкретно поля, которые требуются.

2022-07-24 16:50 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +    private static final String SELECT_FILMS_FRIENDS = "SELECT * FROM FILMS WHERE FILM_ID IN " +
ну и код-стайл самого запроса, ключевые слова в верхнем регистре, название таблиц и полей - в нижнем.

2022-07-24 16:50 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +        List<Film> films = jdbcTemplate.query(SELECT_FILMS_FRIENDS, this::mapRowToFilm, id, id);
Может быть, что бы не поддерживать две реализации извлечения фильмов имеет смысл воспользоваться одной? Т.е. в данном методе получить, например список идентификаторов, а потом пройтись стримом и подергать getById что бы вернуть целые объекты. В противном случае придется дорабатывать оба места, если в фильме еще что-нибудь добавится.

2022-07-24 16:50 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +    public List<Film> getRecommendationsFilms(Long id) {
если вместо id придет null то приложение свалится, так можно оставить, но тогда на уровне сервиса нужно проверить, что бы этот метод не вызвался с null

2022-07-24 16:50 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultRecommendationsService.java
> +    return dbFilmStorage.getRecommendationsFilms(idUser);
idUser будет == null приложение свалится, нужно сделать проверку, таким образом будет работать стабильнее.

2022-07-25 12:10 UTC, culto90 approved these changes
супер!

2022-07-25 18:31 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbFilmStorage.java
> +            " ORDER BY COUNT (film_id) DESC))";
![image](https://user-images.githubusercontent.com/82236220/180848585-3e98c042-23d9-4fdb-8e1f-4e208114d81c.png)

2022-07-25 18:33 UTC, SergeyTsaregorodtsev approved these changes
Круто. SQL команда - просто бомба!

2022-07-25 18:39 UTC, merged