HW Sprint 8.
culto90/java-filmorate pull request #2
Opened 2022-06-06 13:53 UTC by culto90

Хотелось бы получить комменты по следующим вопросам:
1. Валидация ДТО видимо не совсем гибкая штука, лучше, наверное, что бы сервисы валидировали модель или модель саму себя, так наверное гибче можно будет настраивать приложение.
2. Хотелось бы еще пример более красивого оформления конвертеров модель - дто, вариант который приходит в голову сделать более-менее универсально на дженериках

2022-06-06 16:52 UTC, kukolev requested changes

2022-06-06 16:52 UTC, kukolev commented on src/main/java/by/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-06-06 16:52 UTC, kukolev commented on src/main/java/by/yandex/practicum/filmorate/rest/controllers/FilmController.java
> +    public FilmDto newFilm(@Valid @RequestBody FilmDto newFilmDto) throws FilmServiceException {
Нарушение кодстайла: Название метода лучше начинать с глагола, так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-06-06 16:52 UTC, kukolev commented on src/main/java/by/yandex/practicum/filmorate/rest/controllers/UserController.java
> +public class UserController {
Не выполнено требование ТЗ: Не реализовано логирование. Необходимо реализовать согласно ТЗ.

2022-06-06 16:58 UTC, kukolev commented
Ответы на вопросы:

1. Валидация выполнена корректно. Не совсем понятно что имеется в виду под гибкостью. Обычно гибкость подразумевает возможность изменения поведения приложения через настройки. Это при валидации, как правило, не нужно.
2. У вас получились хорошие конвертеры на дженериках. Как вариант можно посмотреть на библиотеки, который упрощают создание конвертеров - Mapstruct, Orika, Dozer и т.п.

2022-06-06 17:51 UTC, culto90 commented
Исправил замечания. У меня почему-то ctrl + alt + L автоматом не удаляет первый пробел после сигнатуры функции. В контроллеры логи явным образом не добавлял, т.к. использую для логирования logbook. Добавил логирование ошибок в хендлеры ошибок.

2022-06-06 22:56 UTC, kukolev requested changes

2022-06-06 22:56 UTC, kukolev commented on src/main/java/by/yandex/practicum/filmorate/services/InMemoryFilmService.java
> +        log.info("Added new film: " + film.toString());
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)`. Так код смотрится проще и не происходит лишняя конкатенация строк, если лог не будет напечатан.

Также нужно поправить в остальных частях кода.

2022-06-07 09:11 UTC, culto90 commented
Исправил замечания по логированию.

2022-06-10 09:52 UTC, merged