Develop
culto90/java-filmorate pull request #29
Opened 2022-07-26 06:22 UTC by culto90

2022-07-26 16:46 UTC, kukolev requested changes
Не хватает тестов. Лучше покрыть тестами основную функциональность.

2022-07-26 16:46 UTC, kukolev commented on src/main/java/by/yandex/practicum/filmorate/models/Director.java
> +public class Director {
По моему лучше использовать аннотации Lombok, чтобы не писать рутинный код. Lombok это уже фактически стандарт в промышленной разработке. Лучше сразу привыкать в полезным практикам.

2022-07-26 16:46 UTC, kukolev commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +        if (!(type.equals("year") || type.equals("likes"))) {
Литералы "year" и "likes" лучше оформить в виде констант или енумов. Это позволит избежать ошибок из-за опечаток и даст больше информации о том, что это такое вообще.

Аналогично нужно поправить в остальных местах программы.

2022-07-26 16:46 UTC, kukolev commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbReviewStorage.java
> +        final String sqlQuery = "SELECT * FROM REVIEWS WHERE FILM_ID = ? ORDER BY useful DESC LIMIT ? ";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-27 11:36 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/models/Director.java
> +public class Director {
исправлено

2022-07-27 11:37 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/models/Feed.java
> +public class Feed {
исправлено

2022-07-27 11:37 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/models/Director.java
> +public class Director {
исправлено

2022-07-27 19:34 UTC, SergeyTsaregorodtsev commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultDirectorService.java
> +        if (!(type.equals("year") || type.equals("likes"))) {
Реализовано через ENUM.

2022-07-29 06:11 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/rest/handlers/GlobalControllerExceptionHandler.java
> +        log.info(ex.getMessage());
исправлено

2022-07-29 08:27 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbLikeReviewStorage.java
> +        String sqlQuery = "INSERT INTO LIKES_REVIEWS (REVIEW_ID, USER_ID, LIKE_TYPE) values (?, ?, ?)";
исправил

2022-07-29 08:27 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/storages/dao/DbReviewStorage.java
> +        final String sqlQuery = "SELECT * FROM REVIEWS WHERE FILM_ID = ? ORDER BY useful DESC LIMIT ? ";
исправил

2022-07-29 09:59 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultReviewService.java
> +        if (review == null) {
исправлено

2022-07-29 10:01 UTC, culto90 commented on src/main/java/by/yandex/practicum/filmorate/services/DefaultReviewService.java
> +        if (review == null) {
исправлено

2022-07-29 10:21 UTC, culto90 commented
Тесты не писали, т.к. пользовались интеграционными https://github.com/yandex-praktikum/java-filmorate/blob/develop/postman/sprint.json

2022-07-29 17:09 UTC, kukolev approved these changes

2022-07-31 13:57 UTC, merged